# Generated by Django 4.2.2 on 2024-06-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Normativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('detalle', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
    ]
