# Generated by Django 4.2.2 on 2024-06-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0002_incidente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidente',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
